### PR TITLE
Redesign with improvements

### PR DESCRIPTION
**Pull request by EverlastEngineering**
- LED2 pulling from 5V_SAFE to avoid higher V on pin1 of Q1. This had an effect of reduce the on saturation of Q2 and limiting overall current slightly. Also this allows a custom value resistor for LED2 to attain a brighter output without affecting the operation of the circuit
- Dual resistors in the divider to make a series resistor combination for a much wider range of custom cutoff values
- The chosen values equate to 3.3kOhm / 3.63kOhm which gives a lower cutoff of 5.25 in testing. 3.3/3.9 increased the cutoff to 5.47V in testing which was too high
- Changed footprint for TO-92 packages to 'ammo' wide lead style for easier soldering by novices
- LED's centered in board for aesthetics when placed in a case with a light pipe / window
- LED placement allows for 5mm LEDs as an option
- Relabeled resistors for easier 'one by one' assembly for novices

### CODE REVIEW

**Comment by EverlastEngineering** [comment]
Obviously, it would have been ideal to use Kicad but I am soooo slow in Kicad right now and needed a design ordered. 

You don't have to merge this, but if you wanna have a look over it it would be helpful. If it looks good I can work on putting the changes into Kicad. One hugely lacking item is I can't do iBom from easyeda pro unfortunately and it's really useful.

**Comment by EverlastEngineering** [comment]
The dual resistor strategy works well for tuning for a specific power supply. If 3.9k is desired you can easily just jumper the missing resistor. It was fun fitting that extra resistor AND wider legs on the two TO-92 packages. All this with no vias! 🔥

**Comment by EverlastEngineering** [comment]
@bwack i redid the design in Kicad.

**Comment by bwack** [comment]
I had a look at the KiCad files just now. Let me know how it goes with the testing. I'm stilll planning to solder up my OCP again with a new mosfet. Just if I can find time and energy.
I see you have thermals on the Q2 footprint. I have dropped thermals on Q2 in my design, and have spread the copper on most of the left side of the board to even out the heat.
Regarding cutoff. That is nice with two resistors, though keep in mind that having the cut-off closer to the PSU voltage  can cause the saver to trip on tansients and noise coming from the AC mains / C64 etc. I was more worried about PSU fault than longevity of RAM in case the PSU is close to 5.4V that I've seen some are.. Other ICs as well its just that the ram is usually the most sensitive.
That's about all I can think of.

**Comment by bwack** [comment]
I just checked the DRC in PCBNew, and it seems that there are no routing errors. I guess your board will work fine :)

**Comment by EverlastEngineering** [comment]
I will wait on this and retest once my MOSFET's arrive on Monday; the 5305 with a 3.6->3.3 voltage divider actually triggers the cutoff on a machine during power off, so those value might need to be reconsidered after further tests.

As far as the thermal breaks, I figure the lower V drop on these mosfets would not need as much conductivity, and it makes it _way_ easier to solder for novices. I'll do some tests of the max temps too!

**Comment by jhiggason** [comment]
All my parts are here except my stupid pcb.  It keeps getting delayed by usps...hope that means it's still coming =/  Hoping to be able to test for you all this week as well. 

When you are doing these tests- I have lots of equipment and could probably at least verify your findings if you can quickly walk through what tests you are doing?  

Anyways this has been fun to be part of- thanks for including me =) If I get this bad boy working properly I plan on updating the BOM with mouser part numbers to make it easier for others.  That silly atpak2 part on the mosfet really threw me for a loop. I'm using chatgpt to try and learn some of this stuff- then verifying with real sources- and chatgpt was adamant that I not use a different part than the atpak2 specifically because atpak2 includes increased cooling efficiency.   In reality, with our parts, it doesn't matter that it's a to-252.  

Thanks again for all this fellas. =)

**Comment by EverlastEngineering** [comment]
Update: the board design works great. As Bwack suggested, the 3.3k + 330 ohm was too low, but 3.9k is too high, so 3.3k + 510 is a nice sweet spot.

I'm going to clean up all the files, move the 2.6 into the old folder, etc, then get a review of the final before the PR.

**Comment by EverlastEngineering** [comment]
Closing this PR and reopening another from a cleaner branch.

**Pull request closed without merging**
